[package]
name = "node-mentant"
version = "0.1.0"
authors = ["Krzysztof Jan Modras <chrmod@chrmod.net>"]
license = "MIT"
build = "build.rs"

[lib]
name = "node_mentant"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.18"

[dependencies]
neon = "0.1.18"
